version: '3'

name: "aloco"

services:
  core:
    build: .
    image: dormammun/aloco:latest
    platform: linux/amd64
    container_name: aloco-core
    restart: always
    environment:
      NODE_ENV: production
      DB_URL: http://surrealdb:8000
    ports:
      - "80:3000"
    networks:
      - services_network

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: aloco-surrealdb
    user: root
    volumes:
      - ~/docker-volumes:/storage
    entrypoint:
      - /surreal
      - start
      - file:/storage/surreal.db
    expose:
      - "8000"
    networks:
      - services_network

networks:
  services_network:
    driver: bridge