import "@/web/common/styles/global.css"
import "@/web/common/styles/tailwind.css"

import type {Metadata} from "next"
import {Inter} from "next/font/google"
import {ReactNode} from "react"

import {PrelineScript} from "@/web/common/components/preline-script"
import {cn} from "@/web/common/utils/cn"

const inter = Inter({subsets: ["latin"]})

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html
      lang="en"
      className={cn(["h-full overflow-auto"])}
    >
      <body className={cn([inter.className, "h-full"])}>{children}</body>
      <PrelineScript />
    </html>
  )
}
