import './_styles/global.css'
import './_styles/tailwind.css'

import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from 'react'

import {PrelineScript} from '@/app/_components/preline-script'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <PrelineScript />
    </html>
  )
}
